### ISSUE TITLE
add explicit support for file urls

### ISSUE THREAD

**Issue by tbonow2o** [gilbarbara/react-inlinesvg#129]
When wrapping up a React app with React-inlinesvg using Electron... the SVGs are not loading. The issue is with the fact that the file is being read locally from a file:// path, not from a server, so doesn't give response headers which is what react-inlinesvg is complaining about when the error comes back with "Content type isn't valid: "

Some smart person at Electron suggested something like the following:

const fs = require('fs');
  const path = require('path');
  const { protocol } = require('electron')
  const { PassThrough } = require('stream')

  function createStream (text) {
    const rv = new PassThrough() 
    rv.push(text)
    rv.push(null)
    return rv
  }

  protocol.registerStreamProtocol('inline-svg', (request, callback) => {
    const url = request.url.replace("inline-svg://", '')
    const filepath = path.normalize(`${__dirname}/${url}`);
    if (filepath.startsWith('..')) {
      callback({
        statusCode: 500,
        headers: {
          'content-type': 'text/plain'
        },
        data: createStream('Internal Error')
      })
    } else {
      callback({
        statusCode: 200,
        headers: {
          'content-type': 'image/svg+xml'
        },
        data: fs.createReadStream(filepath)
      })
    }
  }, (error) => {
    if (error) console.error('Failed to register protocol')
  })

Thank you!

**Comment by gilbarbara** [comment]
Hey,

Loading local files isn't something this library should do. I'll remove that term from the README...
Webpack loaders do that for web apps, they load the file content and set it as a string.

If you need to load something from the file system, you should load it yourself and set the content in the `src` props.

**Comment by gilbarbara** [comment]
The `Content type isn't valid` error must occur because the library is trying to parse `./path/to/file` as a string and that's not valid SVG markup.

Just load the file with `const image = fs.readSync(path, 'utf8')` and use it like `<SVG src={image} />`

**Comment by issacgerges** [comment]
Hey @gilbarbara, thanks for the response. In this case, since @tbonow2o is already loading his app off the `file://` protocol, the relative paths are resolving correctly to other `file://` protocol URLs (so `./path/to/file.svg` is resolving from `file://Users/username/some/directory/index.html` to `file://Users/username/some/directory/path/to/file.svg`. This is a valid URL, but @tbonow2o is getting caught up by this check:  https://github.com/gilbarbara/react-inlinesvg/blob/880785e2660a3a57b0274694a70d0400462c6216/src/index.tsx#L357

By spec, the `file://` protocol does not include any headers. So in his case a change like this would fix his issue.

```
    const contentType = response.headers.get('content-type');
    const [fileType] = (contentType || '').split(/ ?; ?/);
    const isFileProtocol = response.url.startsWith('file://')'
    const hasContentType = ['image/svg+xml', 'text/plain'].some(d => fileType.indexOf(d) >= 0);

      if (response.status > 299) {
        throw new InlineSVGError('Not Found');
      }

      if (!isFileProtocol && !hasContentType) {
        throw new InlineSVGError(`Content type isn't valid: ${fileType}`);
      }

      return response.text();
    })

```

Totally your call if you don't want to support this case, but just wanted to clarify the problem

**Comment by gilbarbara** [comment]
@issacgerges @tbonow2o 

I'm pretty sure that `fetch` can't load `file://...` URLs. You could use a modified fetch for these cases, but I think that loading the file by yourself and using the content is way simpler. This library has support for a lot of cases by using the `src` with a proper SVG string or data input.

This is a simple SVG viewer and adding support for authentication, file system access or any other peculiar requirement isn't something I want to handle.

Why not use [@svgr/webpack](https://www.smooth-code.com/open-source/svgr/docs/webpack/) since bundle size isn't a problem with an Electron app? 
It converts SVGs to React components.

**Comment by issacgerges** [comment]
Makes sense, in electron `file://` is a privileged protocol and does work with `fetch`, but totally see how this makes less sense for you to support.

**Comment by tbonow2o** [comment]
Use @issacgerges code above and built out a new version... works LIKE A CHARM!
