### ISSUE TITLE
Does this support serverside rendering?

### ISSUE THREAD

**Issue by sinn1** [gilbarbara/react-inlinesvg#70]
Since svg is loaded through an XHR request, the serverside rendered dom for the svg element is in the 'pending' state when it's returned to the browser. 

Is there currently any way to turn off loading through XHR if component is rendered on server? 

e.g fall back to 

`<img src={svgUrl} />`

**Comment by gilbarbara** [comment]
I don't think so.
Feel free to open a PR.

**Comment by sinn1** [comment]
Thanks for replying. I'll look into creating a PR when I get some time.

**Comment by gilbarbara** [comment]
@sinn1 
Can you elaborate on your question?

What do you mean by "turn off loading through XHR"? It's the whole point of this package.
The `pending` state is the default because the component still needs to load the SVG file. Or fail and render the fallback.
It will be in that state until `componentDidMount` is triggered, usually when the client opens it in a browser.

Do you want to render the image fallback and not even try to load the SVG?
Why not render the image directly on your side?

**Comment by sinn1** [comment]
Yea I agree regarding the whole point of the package... and I can wrap this component in another component that renders image directly if rendered on serverside.

Was just wondering if there was support for this by default, e.g. through some prop.

**Comment by gilbarbara** [comment]
I think this behavior goes beyond the scope for an async SVG loader.
Cheers
